##############################
# Javascript
##############################

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = '[js, jsx]'
hook_source = '''
let g:vim_jsx_pretty_colorful_config = 1
'''

##############################
# Typescript
##############################

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = '[tsx]'

##############################
# Golang
##############################
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
autocmd FileType go nmap <leader>t <Plug>(go-test)
autocmd FileType go nmap <leader>r <Plug>(go-run)
autocmd FileType go nmap <leader>b <Plug>(go-build)

let g:go_list_type = "quickfix"
let g:go_fmt_command = "goimports"
let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0
let g:go_auto_type_info = 0

" highlight
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_function_calls  = 1
let g:go_highlight_function_parameters = 1
let g:go_highlight_functions = 1
let g:go_highlight_generate_tags = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_types = 1
let g:go_highlight_variable_declarations = 1
let g:go_highlight_variable_assignments = 1
'''
