##############################
# Javascript
##############################

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = '[js, jsx]'
hook_source = '''
let g:vim_jsx_pretty_colorful_config = 1
'''

##############################
# Typescript
##############################

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = '[tsx]'
