##############################
# Javascript(jsx, tsx)
##############################

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = '[jsx, tsx]'
hook_source = '''
let g:vim_jsx_pretty_colorful_config = 1
'''

##############################
# golang
##############################

