##############################
# Vim
##############################
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tomtom/tcomment_vim'

# カッコを入力した時に閉じる方も入力してくれるプラグイン
[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

##############################
# ColorTheme
##############################

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
let g:gruvbox_contrast_dark = 'medium'
'''

##############################
# LSP
##############################

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-ultisnips'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'



[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"
hook_add = '''
source ~/.config/nvim/plugins/coc.rc.vim
'''

